### ISSUE TITLE
I'm stupid

### ISSUE THREAD

**Issue by Cubovskii** [anupammaurya6767/GPT4#5]
😁Onii Chan!
    GPT-4 API
    [0m
The GPT4 API project aims to provide an automated interface for interacting with the GPT-4 (Generative Pre-trained Transformer 4) model developed by OpenAI. GPT-4 is a state-of-the-art natural language processing model capable of generating human-like text based on input prompts.
        
[33mlogin...[33m...
[0mTraceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\api\modules\login.py", line 60, in login
    stay_sign_in = self.wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "[data-testid='post-redirect-form']")))
  File "C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF7A8B01502+60802]
	(No symbol) [0x00007FF7A8A7AC02]
	(No symbol) [0x00007FF7A8937CE4]
	(No symbol) [0x00007FF7A8986D4D]
	(No symbol) [0x00007FF7A8986E1C]
	(No symbol) [0x00007FF7A89CCE37]
	(No symbol) [0x00007FF7A89AABBF]
	(No symbol) [0x00007FF7A89CA224]
	(No symbol) [0x00007FF7A89AA923]
	(No symbol) [0x00007FF7A8978FEC]
	(No symbol) [0x00007FF7A8979C21]
	GetHandleVerifier [0x00007FF7A8E0411D+3217821]
	GetHandleVerifier [0x00007FF7A8E460B7+3488055]
	GetHandleVerifier [0x00007FF7A8E3F03F+3459263]
	GetHandleVerifier [0x00007FF7A8BBB846+823494]
	(No symbol) [0x00007FF7A8A85F9F]
	(No symbol) [0x00007FF7A8A80EC4]
	(No symbol) [0x00007FF7A8A81052]
	(No symbol) [0x00007FF7A8A718A4]
	BaseThreadInitThunk [0x00007FFC3E667344+20]
	RtlUserThreadStart [0x00007FFC404E26B1+33]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Documenti/Developing/Python/Google 2.0 project/Google 2.0.py", line 5, in <module>
    ap.login()
  File "C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\api\gpt4.py", line 48, in login
    self.driver = self.login_handler.login(username, password,self.url)
  File "C:\Users\LENOVO\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\api\modules\login.py", line 69, in login
    raise ElementNotFoundError(f"Element not found: {e}")
api.handlers.exceptions.ElementNotFoundError: Element not found: Message: 
Stacktrace:
	GetHandleVerifier [0x00007FF7A8B01502+60802]
	(No symbol) [0x00007FF7A8A7AC02]
	(No symbol) [0x00007FF7A8937CE4]
	(No symbol) [0x00007FF7A8986D4D]
	(No symbol) [0x00007FF7A8986E1C]
	(No symbol) [0x00007FF7A89CCE37]
	(No symbol) [0x00007FF7A89AABBF]
	(No symbol) [0x00007FF7A89CA224]
	(No symbol) [0x00007FF7A89AA923]
	(No symbol) [0x00007FF7A8978FEC]
	(No symbol) [0x00007FF7A8979C21]
	GetHandleVerifier [0x00007FF7A8E0411D+3217821]
	GetHandleVerifier [0x00007FF7A8E460B7+3488055]
	GetHandleVerifier [0x00007FF7A8E3F03F+3459263]
	GetHandleVerifier [0x00007FF7A8BBB846+823494]
	(No symbol) [0x00007FF7A8A85F9F]
	(No symbol) [0x00007FF7A8A80EC4]
	(No symbol) [0x00007FF7A8A81052]
	(No symbol) [0x00007FF7A8A718A4]
	BaseThreadInitThunk [0x00007FFC3E667344+20]
	RtlUserThreadStart [0x00007FFC404E26B1+33]
I don't know how to fix it :(

**Comment by iCubeVK** [comment]
can someone help?
